### PR TITLE
Added `no std` support

### PR DESCRIPTION
**Pull request by gbip**
I followed @JelteF guidance to implement `no_std` support for this crate (#58).
There might be a few thing that we have to do before merging :
* figure a way to test the `no_std` feature in local (currently it is tested on in CI)
* would mentioning `no_std` support in the crate description be ok for you ?

### CODE REVIEW

**Comment by gbip** [comment]
Hey @JelteF could you take a look at this ? :smile:
I have a crate that depends on this to be published on crates.io.

**Comment by JelteF** [comment]
Thanks for the PR. Could you change it such that the import_root is a global in the utils file? That way it doesn't need to infect the arguments of so many functions in the library. If a global doesn't work for whatever reason a function that returns the import root is also fine. But I think a global should be possible, probably lazy_static is needed though.

**Comment by JelteF** [comment]
@gbip What do you think about the change I suggested?

**Comment by gbip** [comment]
I am willing to apply your changes but I just don't have the time to do this right now... :/

**Comment by JelteF** [comment]
No problem. Mainly wanted to make sure you saw my response.

**Pull request merged**
