### PR TITLE
Derive AsRef and AsMut

### PR DESCRIPTION
**Pull request by reynoldsbd**
Add derives for AsRef and AsMut traits, as discussed [here](https://github.com/JelteF/derive_more/issues/25#issuecomment-530168303).

### CODE REVIEW

**Comment by JelteF** [comment]
Thanks a lot for this PR!

**Comment by reynoldsbd** [comment]
@JelteF happy to contribute!

When can I expect these changes to be published to crates.io?

**Comment by JelteF** [comment]
I expect end of this month, maybe next. I'm planning to make the next
release 0.99 (last before 1.0), which still requires some more work (mostly
cleanup and docs). If you're really in need of a release I can probably
create one earlier.

**Comment by reynoldsbd** [comment]
No rush, just curious :)

Would you be willing to accept a similar PR for Borrow?

**Comment by JelteF** [comment]
Yes, of course. I did change a lot of your original code quite a bit though
so I could use it for other derives too. So be sure to work from the latest
master.

**Comment by JelteF** [comment]
@reynoldsbd are you still planning to send a PR for Borrow?

**Comment by reynoldsbd** [comment]
@JelteF not at this time, turns out I didn't need it

**Comment by Boscop** [comment]
@JelteF @reynoldsbd I'm also interested in support for `Borrow`. Then there is no need to pull in `shrinkwraprs`, too. 
(Reduced compile-time and less ways to do the same thing.)
And more fine-grained control instead of deriving all 3.

**Comment by JelteF** [comment]
@Boscop feel free to send in a PR for `Borrow`. And `DerefMut` and `AsMut` are supported indeed.

**Pull request merged**
