### PR TITLE
Rename and refactor `derive_more::Debug` (#223)

### PR DESCRIPTION
**Pull request by ilslv**
Resolves https://github.com/JelteF/derive_more/issues/223

## Synopsis

#223 

## Solution

Rename `DebugCustom` to `Debug` and change it's logic to be a superset of standard library variant.

## Checklist

- [x] Documentation is updated (if required)
- [x] Tests are added/updated (if required)
- [x] [CHANGELOG entry][l:1] is added (if required)

[l:1]: /CHANGELOG.md

### CODE REVIEW

**Comment by ilslv** [comment]
@tyranron this PR is ready for review.

**Comment by ilslv** [comment]
@tyranron this PR is ready for review

**Review by tyranron — CHANGES_REQUESTED** [review]
@ilslv what a nice job! Thanks!

Reviewing the PR I caught myself multiple times on the feeling that `derive(Debug)` must be separated from `Display`. The semantics differ that much that implementation share only `BoundsAttribute` and `FmtAttribute` parsing, and mixing everything else seems wrong.

So, I propose:
1. Separate `derive(Debug)` implementation into its own `debug` module behind its own `debug` Cargo feature.
2. `BoundsAttribute` and `FmtAttribute` move to `utils` module under `#[cfg(any(feature = "debug", feature = "display")]` and reuse in both `debug` and `display` modules.
3. Have a separate doc for `derive(Debug)` explaining its semantics.
4. Have a separate test suite for `#[derive(Debug)]`.

**Comment by ilslv** [comment]
@tyranron pipeline failed for an unrelated reason and can't restart, but this PR is ready for a review

**Review by tyranron — APPROVED** [review]
@ilslv thanks! After some minor bikesheddings, I'm very pleased with the implementation now.

@JelteF would you like to take a look, or we can merge it?

**Review by JelteF — APPROVED** [review]

**Comment by JelteF** [comment]
Had a look at the test cases and they test all the special cases I could think of. Very nice work!

**Pull request merged**
