### PR TITLE
Add `const` to constructors by a feature

### PR DESCRIPTION
**Pull request by fmiguelgarcia**
Resolves [Constructor generated new should be marked const](https://github.com/JelteF/derive_more/issues/131)

## Synopsis

Added a new `const` feature which generates `const fn` on `Constructor` derives.

## Checklist

- [x] Documentation is updated
- [x] Tests are added/updated **IMPORTANT**: I am not sure if new tests are added to the CI.
- [x] [CHANGELOG entry][l:1] is added

### CODE REVIEW

**Comment by tyranron** [comment]
Should this really be feature-gated? I cannot imagine the situation where `const` will be harmful on constructors.

**Comment by fmiguelgarcia** [comment]
> Should this really be feature-gated? I cannot imagine the situation where `const` will be harmful on constructors.

Just in case you are using a legacy compiler with no support of `const` in Generics.
Having said that, I think `const` feature should be enable by default, WDYT?

att. @tyranron

**Comment by tyranron** [comment]
@fmiguelgarcia well, once we release 1.0 (next release) we will have [MSRV set to 1.65](https://github.com/JelteF/derive_more/issues/202), so you won't be able to use legacy compilers 🤷‍♂️

**Comment by JelteF** [comment]
Also, I feel like the same should be done for the `IsVariant` and `Unwrap` derives.

**Comment by tyranron** [comment]
@JelteF `IsVariant` yes, but `Unwrap` definitely not, as `const` at the moment is not very clever with destructor evaluation checks, so almost any struct/enum destruction in `const` leads to compilation error. See https://github.com/rust-lang/rust/issues/60964 for details.

**Comment by fmiguelgarcia** [comment]
@tyranron I've used the `const` feature to enable const in `Unwrap` (I've just read your comment).
`IsVariant` and `Constructor` now uses `const fn`.

Do you want to remove `const` feature completely? Or Do you want to keep it and support `const` in `Unwrap`? 
att. @JelteF @tyranron

**Comment by tyranron** [comment]
@fmiguelgarcia I'd vote for removing `const` feature completely. We always may `const`ify `Unwrap` once `feature(const_precise_live_drops)` is stabilized. It's not something that vital, deserving to squat-around it with an additional Cargo feature.

**Comment by JelteF** [comment]
I think this is almost good to merge, just a few things are needed:
1. Remove const from unwrap due to the bugs (so only const for constructor and isvariant for now)
2. Remove the const feature and simply always use const.
3. fix clippy errors.

**Comment by JelteF** [comment]
@fmiguelgarcia do you have time to do that? This is one of the final things left on the 1.0.0 milestone.

**Review by JelteF — APPROVED** [review]

**Pull request merged**
